
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: unpaywall_develop

test:
  <<: *default
  database: unpaywall_test

production:
  <<: *default
  database: unpaywall
  username: api
  password: <%= ENV["API_DATABASE_PASSWORD"] %>
